package com.redemption.backend.entities;

import jakarta.persistence.*;

/**
 * Entity class representing a reward that users can redeem using their points.
 */
@Entity
@Table(name = "rewards") // Maps this entity to the "rewards" table in the database
public class Reward {

    // Unique identifier for each reward (auto-generated by the database)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long rewardId;

    // Name/title of the reward (e.g., Seaweed Shopping Bag)
    private String rewardName;

    // Description of the reward (optional detail)
    private String description;

    // Number of points required to redeem this reward
    private int pointsRequired;

    // ----- Constructors -----

    /**
     * Default no-args constructor (required by JPA).
     */
    public Reward() {}

    // ----- Getters -----

    /**
     * Gets the reward ID.
     * @return the unique ID of the reward.
     */
    public Long getRewardId() {
        return rewardId;
    }

    /**
     * Gets the reward name.
     * @return the name/title of the reward.
     */
    public String getRewardName() {
        return rewardName;
    }

    /**
     * Gets the reward description.
     * @return a description of the reward.
     */
    public String getDescription() {
        return description;
    }

    /**
     * Gets the number of points required to redeem the reward.
     * @return points required for redemption.
     */
    public int getPointsRequired() {
        return pointsRequired;
    }

    // ----- Setters -----

    /**
     * Sets the reward ID.
     * @param rewardId the unique ID to assign.
     */
    public void setRewardId(Long rewardId) {
        this.rewardId = rewardId;
    }

    /**
     * Sets the reward name.
     * @param rewardName the name of the reward.
     */
    public void setRewardName(String rewardName) {
        this.rewardName = rewardName;
    }

    /**
     * Sets the reward description.
     * @param description a description of the reward.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Sets the number of points required to redeem the reward.
     * @param pointsRequired number of points needed.
     */
    public void setPointsRequired(int pointsRequired) {
        this.pointsRequired = pointsRequired;
    }
}
